// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_Pl_svNtSoIYISk5BykyIRVIwImtk2WY',
    appId: '1:687940734579:web:82ac51ab588809da656406',
    messagingSenderId: '687940734579',
    projectId: 'chat-f9d30',
    authDomain: 'chat-f9d30.firebaseapp.com',
    storageBucket: 'chat-f9d30.appspot.com',
    measurementId: 'G-8T7QJSXYD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpNUdeoEWZCuLRp8Z8ULaOnUhIHb3RS2c',
    appId: '1:687940734579:android:e025550a5694c240656406',
    messagingSenderId: '687940734579',
    projectId: 'chat-f9d30',
    storageBucket: 'chat-f9d30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW6aLQoASE5LxGtmoycl7WGNlAXo0Yfk0',
    appId: '1:687940734579:ios:8eb86095bdb3fc40656406',
    messagingSenderId: '687940734579',
    projectId: 'chat-f9d30',
    storageBucket: 'chat-f9d30.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW6aLQoASE5LxGtmoycl7WGNlAXo0Yfk0',
    appId: '1:687940734579:ios:8eb86095bdb3fc40656406',
    messagingSenderId: '687940734579',
    projectId: 'chat-f9d30',
    storageBucket: 'chat-f9d30.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_Pl_svNtSoIYISk5BykyIRVIwImtk2WY',
    appId: '1:687940734579:web:290d324def5e3ed8656406',
    messagingSenderId: '687940734579',
    projectId: 'chat-f9d30',
    authDomain: 'chat-f9d30.firebaseapp.com',
    storageBucket: 'chat-f9d30.appspot.com',
    measurementId: 'G-BRXPG1JXCY',
  );
}
